name: stockfish_for_mobile
description: The Stockfish Chess Engine for Flutter (ios / android) credits go to Arjan Aswal and loloof64.
version: 1.1.2
repository: https://github.com/Yavmarto/stockfish.git
homepage: https://github.com/Yavmarto/stockfish.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  ffi: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.stockfish
        pluginClass: StockfishPlugin
      ios:
        pluginClass: StockfishPlugin
